'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EODSchedulerDetail
    Public Property PK_EODSchedulerDetail_ID As Long
    Public Property FK_EODSCheduler_ID As Nullable(Of Long)
    Public Property FK_EODTask_ID As Nullable(Of Long)
    Public Property OrderNo As Nullable(Of Integer)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)

End Class
