'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EODScheduler
    Public Property PK_EODScheduler_ID As Long
    Public Property EODSchedulerName As String
    Public Property EODSchedulerDescription As String
    Public Property EODPeriod As Nullable(Of Integer)
    Public Property FK_MsEODPeriod As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property HasPeriodikScheduler As Nullable(Of Boolean)

End Class
