'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EODTaskDetailLog
    Public Property PK_EODTaskDetailLog_ID As Long
    Public Property EODSchedulerLogID As Nullable(Of Long)
    Public Property EODTaskLogID As Nullable(Of Long)
    Public Property FK_EODTAskDetail_ID As Nullable(Of Long)
    Public Property ExecuteBy As String
    Public Property StartDate As Nullable(Of Date)
    Public Property Enddate As Nullable(Of Date)
    Public Property ErrorMessage As String
    Public Property FK_MsEODStatus_ID As Nullable(Of Integer)
    Public Property executionID As String

End Class
