'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EODTaskDetail
    Public Property PK_EODTaskDetail_ID As Long
    Public Property FK_EODTask_ID As Nullable(Of Long)
    Public Property FK_EODTaskDetailType_ID As Nullable(Of Integer)
    Public Property OrderNo As Nullable(Of Integer)
    Public Property SSISName As String
    Public Property SSISFIle As Byte()
    Public Property StoreProcedureName As String
    Public Property Keterangan As String
    Public Property IsUseParameterProcessDate As Nullable(Of Boolean)

End Class
