'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LogConsoleService
    Public Property Pk_LogConsoleService_Id As Long
    Public Property LogCreatedDate As Nullable(Of Date)
    Public Property LogStatus As String
    Public Property LogInfo As String
    Public Property LogDescription As String

End Class
