'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NawaDataETLConfiguration
    Public Property ConfigurationFilter As String
    Public Property ConfiguredValue As String
    Public Property PackagePath As String
    Public Property ConfiguredValueType As String

End Class
