'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class NawaDataEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NawaDataEntities")
		DirectCast(Me, IObjectContextAdapter).ObjectContext.CommandTimeout = 36000
MyBase.Configuration.ProxyCreationEnabled  = False
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property EODSchedulers() As DbSet(Of EODScheduler)
    Public Property EODSchedulerDetails() As DbSet(Of EODSchedulerDetail)
    Public Property EODSchedulerLogs() As DbSet(Of EODSchedulerLog)
    Public Property EODTasks() As DbSet(Of EODTask)
    Public Property EODTaskDetails() As DbSet(Of EODTaskDetail)
    Public Property EODTaskDetailLogs() As DbSet(Of EODTaskDetailLog)
    Public Property EODTaskDetailTypes() As DbSet(Of EODTaskDetailType)
    Public Property EODTaskLogs() As DbSet(Of EODTaskLog)
    Public Property SystemParameters() As DbSet(Of SystemParameter)
    Public Property LogConsoleServices() As DbSet(Of LogConsoleService)
    Public Property TrxDafnom_Print() As DbSet(Of TrxDafnom_Print)
    Public Property TrxDafnom_OTP() As DbSet(Of TrxDafnom_OTP)
    Public Property TrxDafnoms() As DbSet(Of TrxDafnom)
    Public Property TrxOTP_NCBSFile() As DbSet(Of TrxOTP_NCBSFile)
    Public Property TrxOTP_Angsuran() As DbSet(Of TrxOTP_Angsuran)
    Public Property TrxDafnom_Detail() As DbSet(Of TrxDafnom_Detail)
    Public Property Vw_MigrasiAngsuran() As DbSet(Of Vw_MigrasiAngsuran)
    Public Property NawaDataETLConfigurations() As DbSet(Of NawaDataETLConfiguration)
    Public Property TrxOTP_Pelunasan() As DbSet(Of TrxOTP_Pelunasan)
    Public Property TrxLimits() As DbSet(Of TrxLimit)

End Class
