'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SystemParameter
    Public Property PK_SystemParameter_ID As Integer
    Public Property FK_SystemParameterGroup_ID As Nullable(Of Integer)
    Public Property SettingName As String
    Public Property SettingValue As String
    Public Property Active As Nullable(Of Boolean)
    Public Property Hide As Nullable(Of Boolean)
    Public Property fk_MFieldType_ID As Nullable(Of Integer)
    Public Property IsEncript As Nullable(Of Boolean)
    Public Property EncriptionKey As String

End Class
