'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrxDafnom_Print
    Public Property Pk_TrxDafnom_Print_Id As Long
    Public Property Fk_TrxDafnom_Id As Nullable(Of Long)
    Public Property AttachmentFileName As String
    Public Property AttachmentFileContent As Byte()

End Class
