'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrxDafnom
    Public Property Pk_TrxDafnom_Id As Long
    Public Property Fk_MsKoperasi_Id As Nullable(Of Long)
    Public Property Fk_TrxLimit_Id As Nullable(Of Long)
    Public Property Batch As Nullable(Of Integer)
    Public Property TotalPengajuan As Nullable(Of Decimal)
    Public Property Fk_MsStatusDafnom_Id As Nullable(Of Integer)
    Public Property Fk_MsStatusDokumen_Id As Nullable(Of Integer)
    Public Property ApprovalReason As String
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)

    Public Overridable Property TrxDafnom_OTP As ICollection(Of TrxDafnom_OTP) = New HashSet(Of TrxDafnom_OTP)
    Public Overridable Property TrxDafnom_Detail As ICollection(Of TrxDafnom_Detail) = New HashSet(Of TrxDafnom_Detail)

End Class
