'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrxLimit
    Public Property Pk_TrxLimit_Id As Integer
    Public Property Fk_MsKoperasi_Id As Integer
    Public Property NoSPK As String
    Public Property TanggalTenorMax As Nullable(Of Date)
    Public Property TanggalTarikMax As Date
    Public Property Plafond As Nullable(Of Decimal)
    Public Property Outstanding As Nullable(Of Decimal)
    Public Property Fk_MsStatusLimit_Id As Integer
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property LimitCode As String
    Public Property BookingLoan As String
    Public Property Margin As Nullable(Of Decimal)
    Public Property SukuBunga As Nullable(Of Decimal)
    Public Property ProductCodeMIS As String
    Public Property ProductCodeNCBS As String
    Public Property ParentLimitCode As String
    Public Property MsBranchCode As String
    Public Property SisaLimit As Nullable(Of Decimal)
    Public Property CappingDeviasi As Nullable(Of Decimal)
    Public Property CappingPlafon As Nullable(Of Decimal)
    Public Property CappingPlafonPercent As Nullable(Of Decimal)
    Public Property CappingIIR As Nullable(Of Decimal)
    Public Property CappingIIRPercent As Nullable(Of Decimal)
    Public Property ScheduleCode As String

End Class
