'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrxOTP_Angsuran
    Public Property Pk_TrxOTP_Angsuran_Id As Long
    Public Property Fk_TrxDafnom_OTP_Id As Nullable(Of Long)
    Public Property Fk_TrxDafnom_Detail_Id As Nullable(Of Long)
    Public Property AngsuranKe As Nullable(Of Integer)
    Public Property TanggalAngsuran As Nullable(Of Date)
    Public Property SisaPokok As Nullable(Of Decimal)
    Public Property AngsuranPokok As Nullable(Of Decimal)
    Public Property AngsuranMargin As Nullable(Of Decimal)
    Public Property TotalAngsuran As Nullable(Of Decimal)

End Class
