'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrxOTP_Pelunasan
    Public Property Pk_TrxOTP_Pelunasan_Id As Long
    Public Property Fk_TrxDafnom_OTP_Id As Nullable(Of Long)
    Public Property Fk_MsJenisOTPPelunasan_Id As Nullable(Of Integer)
    Public Property TotalPelunasan As Nullable(Of Decimal)
    Public Property Fk_MsJenisRecalculatePelunasan_Id As Nullable(Of Integer)
    Public Property Fk_MsStatusPelunasan_Id As Nullable(Of Integer)
    Public Property Fk_MsStatusDokumen_Id As Nullable(Of Integer)
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property LastUpdateDate As Nullable(Of Date)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property ApprovalReason As String
    Public Property TotalOutstanding As Nullable(Of Decimal)
    Public Property TotalMarginBerjalan As Nullable(Of Decimal)
    Public Property TunggakanMargin As Nullable(Of Decimal)
    Public Property TunggakanDenda As Nullable(Of Decimal)
    Public Property No_Urut As Nullable(Of Integer)

End Class
