'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrxOTP_NCBSFile
    Public Property Pk_TrxOTP_NCBSFile_Id As Long
    Public Property Fk_TrxDafnom_OTP_Id As Nullable(Of Long)
    Public Property NCBSFileName As String
    Public Property NCBSFileContent As Byte()
    Public Property Fk_MsStatusPengiriman_Id As Nullable(Of Integer)
    Public Property Fk_MsNCBSFileType_Id As Nullable(Of Integer)
    Public Property GeneratedDate As Nullable(Of Date)
    Public Property SendDate As Nullable(Of Date)
    Public Property ResponseDate As Nullable(Of Date)
    Public Property ErrorMessage As String
    Public Property ResponseFileName As String
    Public Property ResponseFileContent As Byte()

End Class
