'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vw_MigrasiAngsuran
    Public Property CIFNo As String
    Public Property LimitCode As String
    Public Property Batch As Nullable(Of Short)
    Public Property Fk_TrxDafnom_Id As Long
    Public Property Tenor As Byte
    Public Property Fk_MsJenisOTP_Id As Integer
    Public Property TanggalPencairan As Nullable(Of Date)
    Public Property Nominal As Nullable(Of Decimal)
    Public Property NisbahBagiHasilBank As Integer
    Public Property NisbahBagiHasilNasabah As Integer
    Public Property Fk_MsKondisiMargin_Id As Integer
    Public Property TanggalDebetAngsuran As Nullable(Of Integer)
    Public Property Fk_MsJenisPencairan_Id As Integer
    Public Property Fk_MsStatusOTP_Id As Integer
    Public Property Fk_MsStatusDokumen_Id As Integer
    Public Property CreatedBy As String
    Public Property LastUpdateBy As String
    Public Property ApprovedBy As String
    Public Property CreatedDate As Date
    Public Property LastUpdateDate As Date
    Public Property ApprovedDate As Date
    Public Property ApprovalReason As String
    Public Property LTSApprovalReason As String
    Public Property AccountNo As String
    Public Property NomorRekeningCASA As String
    Public Property MarginEquivalent As Nullable(Of Decimal)
    Public Property Pk_TrxDafnom_OTP_Id As Long

End Class
